
-- camping_original_sites
CREATE TABLE IF NOT EXISTS public.camping_original_sites
(
    id                                             integer,
    facility_name                                  varchar(255),
    category                                       varchar(255),
    city_province_name                             varchar(255),
    city_county_district_name                      varchar(255),
    administrative_area_name                       varchar(255),
    ri_name                                        varchar(255),
    street_address                                 varchar(255),
    road_name                                      varchar(255),
    building_number                                varchar(255),
    latitude                                       double precision,
    longitude                                      double precision,
    postal_code                                    varchar(20),
    street_name_address                            varchar(255),
    full_street_address                            varchar(255),
    telephone_number                               varchar(20),
    website                                        varchar(255),
    business_entity                                varchar(255),
    operate_weekdays_yn                            boolean,
    operate_weekends_yn                            boolean,
    operate_spring_yn                              boolean,
    operate_summer_yn                              boolean,
    operate_fall_yn                                boolean,
    operate_winter_yn                              boolean,
    electricity_auxiliary_facilities_yn            boolean,
    hot_water_auxiliary_facilities_yn              boolean,
    wireless_internet_auxiliary_facilities_yn      boolean,
    firewood_sales_auxiliary_facilities_yn         boolean,
    promenade_auxiliary_facilities_yn              boolean,
    water_park_auxiliary_facilities_yn             boolean,
    playground_auxiliary_facilities_yn             boolean,
    mart_auxiliary_facilities_yn                   boolean,
    restrooms_auxiliary_facilities                 integer,
    shower_rooms_auxiliary_facilities              integer,
    sinks_auxiliary_facilities                     integer,
    fire_extinguishers_auxiliary_facilities        integer,
    fishing_nearby_facilities_yn                   boolean,
    promenade_nearby_facilities_yn                 boolean,
    water_play_sea_bathing_nearby_facilities_yn    boolean,
    water_play_sea_leisure_nearby_facilities_yn    boolean,
    water_play_valley_nearby_facilities_yn         boolean,
    water_play_river_nearby_facilities_yn          boolean,
    water_play_pool_nearby_facilities_yn           boolean,
    youth_experience_facility_nearby_facilities_yn boolean,
    rural_experience_facility_nearby_facilities_yn boolean,
    childrens_play_facility_nearby_facilities_yn   boolean,
    glamping_bed_yn                                boolean,
    glamping_tv_yn                                 boolean,
    glamping_refrigerator_yn                       boolean,
    glamping_internet_wired_wireless_yn            boolean,
    glamping_interior_restroom_yn                  boolean,
    glamping_air_conditioner_yn                    boolean,
    glamping_heating_equipment_yn                  boolean,
    glamping_cooking_utensils_yn                   boolean,
    facility_features                              text,
    facility_introduction                          text,
    last_written_date                              date,
    ctprvn_cd                                      varchar(2),
    sig_cd                                         varchar(5)
    );

alter table public.camping_original_sites
    owner to postgres;
